dist: bionic

language: python

arch:
    - amd64
    - arm64

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

matrix:
    include:
        - os: osx
          language: generic

install:
    - pip3 install -r requirements-dev.txt

script:
    - ./run_tests
